markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences

nav:
  - Getting Started: index.md
  - Best Practices: best-practices.md
  - Jest Snippets Book: jest-snippets-book.md

site_name: "Testing Vue Components"

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
